FROM node:24-bookworm-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends curl ca-certificates \
    && rm -rf /var/lib/apt/lists/*

RUN curl -fsSL https://rover.apollo.dev/nix/latest | sh -s -- --elv2-license accept

ENV PATH="/root/.rover/bin:${PATH}"
WORKDIR /app

CMD ["rover", "--version"]
